In [57]:
# verify convex combination


import numpy as np

import matplotlib.pyplot as plt


x = np.random.random_integers(10, size=(6,2))
x = np.array([[1,1],[2,2], [1,2], [2,1]])

points = []

for i in range(100):
    for j in range(i):
        points.append((j/100.0) * x[0,:] + ((i/100.0)-(j/100.0)) * x[1,:] + (1-(i/100.0)) * x[2,:])
    
points = np.array(points)

print(points.shape)
z = np.ones(points.shape[0])
plt.scatter(points[:,0], points[:,1], c=z, s=100, cmap=plt.cm.cool, edgecolors='None', alpha=0.75)
plt.colorbar()
plt.show()


(4950, 2)


In [53]:
# verify linear indepent

# in x,y in r^2, { z = ax + by for all z in r^2 if x,y are independent}

import numpy as np
import matplotlib.pyplot as plt

x = np.random.uniform(-1,1,2)

y =  np.random.uniform(-1,1,2)
#y = x*33


# select random integers
zx =  np.random.uniform(-5,5,200)

zy =  np.random.uniform(-5,5,200)


print(x)
print(y)
#print(a)
#print(b)
z = []
for i in range(zx.shape[0]):
    # see if you can prove (zx,zy) = [x,y] * [a,b].T
    a,b,c,d = x[0],x[1],y[0],y[1]
        
    c1 = (zx[i]/c - zy[i]/d)/(a/c - b/d)
    
    c2 =  (zx[i]/a - zy[i]/b)/(c/a - d/b)
    
    print(c1,c2, x,y, [c1* x[0] + c2 *y[0]], [zx[i]], [c1* x[1] + c2 *y[1]], [zy[i]])
    
    
    
plt.show()
    


[-0.34839011  0.51749611]
[-0.32650286  0.92359512]
12.9193369597 -9.0334645753 [-0.34839011  0.51749611] [-0.32650286  0.92359512] [-1.5515172046382411] [-1.5515172046382419] [-1.657557236189569] [-1.6575572361895672]
-1.03181409691 2.901276727 [-0.34839011  0.51749611] [-0.32650286  0.92359512] [-0.587801326413665] [-0.58780132641366478] [2.1456452488042359] [2.1456452488042359]
-10.8073438094 6.53650301264 [-0.34839011  0.51749611] [-0.32650286  0.92359512] [1.6309847721531194] [1.6309847721531199] [0.44432395283355053] [0.44432395283354964]
-20.4794473241 13.3628083443 [-0.34839011  0.51749611] [-0.32650286  0.92359512] [2.7718417652132361] [2.771841765213237] [1.7437903438587981] [1.7437903438587963]
28.7344689652 -15.5881449283 [-0.34839011  0.51749611] [-0.32650286  0.92359512] [-4.921230910110288] [-4.9212309101102907] [0.47284119477508746] [0.47284119477509101]
17.0395974578 -9.4424383062 [-0.34839011  0.51749611] [-0.32650286  0.92359512] [-2.8534441245274951] [-2.85344412452

In [8]:
import numpy as np
import matplotlib.pyplot as plt
soa =np.array( [ [0,0,3,2], [0,0,1,1],[0,0,9,9]]) 
X,Y,U,V = zip(*soa)
plt.figure()
print(X, Y, U, V)
ax = plt.gca()
ax.quiver(X, Y, U, V, angles='xy',scale_units='xy',scale=1)
ax.set_xlim([-1,10])
ax.set_ylim([-1,10])
plt.draw()
plt.show()

(0, 0, 0) (0, 0, 0) (3, 1, 9) (2, 1, 9)


In [28]:
# back tracking 

import matplotlib.pyplot as plt
import numpy as np
from plotly.tools import FigureFactory as FF

def f(x):
    return np.cos(x)

def df(x):
    return -1 * np.sin(x)

x = np.arange(2, 4.5, 0.1)
y = np.cos(x)
plt.plot(x, y)

# rat x = -2
fx = 2.5 
t = np.arange(0, 1, 0.1)

# f(x) + t * d(f(x)) * d(x)
# d(f(x)) = 2 * x = -4 
# d(x) = postive = 1
# @ x = -2
# 4 + (t * -4 * 1)
print(t + fx)
print(f(fx) + (t * df(fx) * 1))
plt.plot(t + fx, f(fx) + (t * df(fx) * 1))

# alpha = 0.3
a = 0.3
plt.plot(t + fx,  f(fx) + a * (t * df(fx) * 1))
plt.show()


[ 2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4]
[-0.80114362 -0.86099083 -0.92083804 -0.98068526 -1.04053247 -1.10037969
 -1.1602269  -1.22007412 -1.27992133 -1.33976855]


In [37]:
# loss functions
import matplotlib.pyplot as plt
import numpy as np
x = np.arange(0.1,2,0.1)

#desired value = 1

# (x - 1)**2
plt.plot(x, (x - 1)**2)
# |log(x) - log(1)|
plt.plot(x, abs(np.log(x) - np.log(1)))
# |log(x) - log(1)|**2
plt.plot(x, (abs(np.log(x) - np.log(1))**2))

plt.show()


In [55]:
import numpy as np
import matplotlib.pyplot as plt

# strong convexity
x = np.arange(-5, 5, 0.1)

for i in range(1,11,2):
    plt.plot(x, i/2 * x**2, label='{} strongly convex'.format(i))
    
plt.legend()
    
plt.show()

In [11]:
# understanding dot product
import numpy as np
import matplotlib.pyplot as plt


x = np.random.randint(-5,5,100)


y = (2-5*x)/5

print([i for i in zip(x,y)])

plt.plot(x, y)
plt.show()


[(-5, 5.4000000000000004), (-4, 4.4000000000000004), (-3, 3.3999999999999999), (1, -0.59999999999999998), (1, -0.59999999999999998), (-2, 2.3999999999999999), (-3, 3.3999999999999999), (3, -2.6000000000000001), (-3, 3.3999999999999999), (3, -2.6000000000000001), (2, -1.6000000000000001), (0, 0.40000000000000002), (4, -3.6000000000000001), (2, -1.6000000000000001), (3, -2.6000000000000001), (0, 0.40000000000000002), (-3, 3.3999999999999999), (4, -3.6000000000000001), (-2, 2.3999999999999999), (-3, 3.3999999999999999), (-2, 2.3999999999999999), (-2, 2.3999999999999999), (1, -0.59999999999999998), (-3, 3.3999999999999999), (-5, 5.4000000000000004), (1, -0.59999999999999998), (3, -2.6000000000000001), (0, 0.40000000000000002), (-1, 1.3999999999999999), (4, -3.6000000000000001), (-2, 2.3999999999999999), (-4, 4.4000000000000004), (0, 0.40000000000000002), (2, -1.6000000000000001), (-5, 5.4000000000000004), (4, -3.6000000000000001), (2, -1.6000000000000001), (-1, 1.3999999999999999), (0, 0.4

In [6]:
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.gca(projection='3d')

m = np.array([[1,3,4], [1,1,5]])

print(m)
print(m[:,0], m[:,1], m[:,2])

ax.scatter(m[:,0], m[:,1], m[:,2], c='r')

l1 = np.random.random_integers(-5,5,
                              100)
l2 = np.random.random_integers(-5,5,100)

l = np.array([l1,l2])

r = np.array((np.matrix(m).T * np.matrix(l)))

print(r)
print(r[0])
ax.plot_surface(r[0], r[1], r[2])





ax.legend()
ax.set_xlim3d(-50, 50)
ax.set_ylim3d(-50, 50)
ax.set_zlim3d(-50, 50)

plt.show()

[[1 3 4]
 [1 1 5]]
[1 1] [3 1] [4 5]
[[  7  -1  -8  -1   1   0  -5  -6  10  -2  -1  -5  -7  -2   4   5   8   5
    4  -1   5   7  -5  -4   2   5   1   2  -3  -1   3  -1  -3   1  -5  -8
   -5  -4  -3   1   1  -1   0  -1   3   4   2  -1   4  -1  -8  -2  -9   5
    1   0   5  -3  -3   5  -5   3  -3  -5   1  -5  -3  -3  -3   5  -2  -8
    4   4   2  -9   6  -3   3   3  -5   5  -7   1   0  -7   0   4   4   1
   -1   6  -4   3   3   4   6   0   2  -1]
 [ 15  -9 -18   7  -3  -6 -15 -14  20  -8   5 -15 -17  -6   8   7  14   9
   12  -3  15  15  -7 -12   6  15   9   6  -5 -11   3  -5 -11   1  -5 -16
   -5  -2  -9   3   5  -5  -8   3  13  12   6   1   4  -9 -18   4 -17  15
    5  -8  15 -11  -1  15  -9  13 -13 -13  -5 -11 -13  -5 -13  11  -4 -18
   14  14  -2 -17  12  -5   1   5  -9   9 -13   9   2 -15   8   8  12   9
    7  14  -6  13  13  12  10   4   0   5]
 [ 31  -1 -35  -9   7   3 -20 -26  45  -7  -8 -20 -30  -8  18  24  37  23
   16  -4  20  31 -24 -16   8  20   1   8 -14   0  15  -3 -11  

C:\Users\serajago.FAREAST\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py:519: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


In [5]:
# misc

import math
import matplotlib.pyplot as plt
import numpy as np

def normDistance(minD, medD, distance):
    return math.sqrt(min(1, (minD + medD) / (distance + medD)))


minD = np.array([0,1,5,10,30,60,160])
minD = 20
medD = np.array([1,2,3,5,10,15,30,60,100])
medD = [minD + 0]

style = ['.', ',', 'o', 'v', '^', '<', '.', '1','2','3','4']

count = 0
for m in medD:
    distance = np.array([i for i in range(0, 200)])   
    distance += minD
    nd = distance + m
    nd = (minD + m)/nd
    nd = np.minimum(1, nd)
    nd = np.sqrt(nd)
    
    normDistance = nd
    #print(distance, nd)
    
    plt.plot(distance, normDistance, label='{}'.format(m), marker=style[count])
    

    
    count+=1
    
distance = np.array([i for i in range(0, 200)]) 
distance += minD
normDistance = np.array([0.5] * len(distance))
plt.plot(distance, normDistance, label='{}'.format('median'))


                           
plt.legend()
    
plt.show()










In [151]:
# misc, min , max range penality

import math
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

data = genfromtxt(r'E:\\Temp\\minMed.tsv', delimiter='\t')
x = np.arange(500)
print(x)
plt.plot(x, np.maximum(0, 1-((x/200)**2.1)))
plt.show()

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [29]:
# norm ball 

from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator
import matplotlib.pyplot as plt
import numpy as np



fig = plt.figure()
ax = fig.gca(projection='3d')
ax.set_aspect('equal')



u, v = np.mgrid[0:2*np.pi:50j, 0:np.pi:25j]

X=np.cos(u)*np.sin(v)
Y=np.sin(u)*np.sin(v)
Z=np.cos(v)

xlen = len(X)
ylen = len(Y)

surf = ax.plot_surface(X, Y, Z, rstride=1, cstride=1,
                       linewidth=0, antialiased=True, alpha=0.1, color='r')



plt.show()
    

Courtesy of MathJax, you can include mathematical expressions both inline: 
    $e^{i\pi} + 1 = 0$  